export const data = {
    menuItems: {
        1: [
            {
                0: "2",
                media_id: "2",
                1: "ارز",
                menus_name: "ارز",
                2: "Rr",
                description: "Rr",
                3: "20",
                menus_price: "20",
                4: "1",
                category_id: "1",
                5: "1000140229.jpg",
                image: "1000140229.jpg",
            },
            {
                0: "3",
                media_id: "3",
                1: "Qr",
                menus_name: "Qr",
                2: "33",
                description: "33",
                3: "2",
                menus_price: "2",
                4: "1",
                category_id: "1",
                5: "1000155039.jpg",
                image: "1000155039.jpg",
            },
            {
                0: "7",
                media_id: "7",
                1: "ارز",
                menus_name: "ارز",
                2: "Rr",
                description: "Rr",
                3: "20",
                menus_price: "20",
                4: "1",
                category_id: "1",
                5: "1000157068.jpg",
                image: "1000157068.jpg",
            },
        ],
        2: [
            {
                0: "11",
                media_id: "11",
                1: "086",
                menus_name: "086",
                2: "اسود",
                description: "اسود",
                3: "1.5",
                menus_price: "1.5",
                4: "3",
                category_id: "3",
                5: "1000157215.jpg",
                image: "1000157215.jpg",
            },
            {
                0: "12",
                media_id: "12",
                1: "375",
                menus_name: "375",
                2: "بني",
                description: "بني",
                3: "0",
                menus_price: "0",
                4: "4",
                category_id: "4",
                5: "1000157213.jpg",
                image: "1000157213.jpg",
            },
            {
                0: "13",
                media_id: "13",
                1: "375",
                menus_name: "375",
                2: "بني",
                description: "بني",
                3: "0",
                menus_price: "0",
                4: "4",
                category_id: "4",
                5: "1000157213.jpg",
                image: "1000157213.jpg",
            },
            {
                0: "14",
                media_id: "14",
                1: "018",
                menus_name: "018",
                2: "1",
                description: "1",
                3: "0",
                menus_price: "0",
                4: "5",
                category_id: "5",
                5: "1000157212.jpg",
                image: "1000157212.jpg",
            },
            {
                0: "15",
                media_id: "15",
                1: "018",
                menus_name: "018",
                2: "1",
                description: "1",
                3: "0",
                menus_price: "0",
                4: "5",
                category_id: "5",
                5: "1000157212.jpg",
                image: "1000157212.jpg",
            },
        ],
        3: [
            {
                0: "26",
                media_id: "26",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "images.jpeg",
                image: "images.jpeg",
            },
            {
                0: "27",
                media_id: "27",
                1: "كلاسيك لحم",
                menus_name: "كلاسيك لحم",
                2: "برجر كلاسيك لحم",
                description: "برجر كلاسيك لحم",
                3: "2.5",
                menus_price: "2.5",
                4: "6",
                category_id: "6",
                5: "images-(3).jpeg",
                image: "images-(3).jpeg",
            },
            {
                0: "30",
                media_id: "30",
                1: "برجر مشروم",
                menus_name: "برجر مشروم",
                2: "برجر مشروم",
                description: "برجر مشروم",
                3: "2.5",
                menus_price: "2.5",
                4: "6",
                category_id: "6",
                5: "images-(7).jpeg",
                image: "images-(7).jpeg",
            },
            {
                0: "32",
                media_id: "32",
                1: "رد بول",
                menus_name: "رد بول",
                2: "مشروب الطاقة رد بول",
                description: "مشروب الطاقة رد بول",
                3: "1.25",
                menus_price: "1.25",
                4: "7",
                category_id: "7",
                5: "images-(11).jpeg",
                image: "images-(11).jpeg",
            },
            {
                0: "33",
                media_id: "33",
                1: "كود رِد",
                menus_name: "كود رِد",
                2: "مشروب الطاقة كود رِد",
                description: "مشروب الطاقة كود رِد",
                3: "1",
                menus_price: "1",
                4: "7",
                category_id: "7",
                5: "images-(12).jpeg",
                image: "images-(12).jpeg",
            },
            {
                0: "34",
                media_id: "34",
                1: "سوبر",
                menus_name: "سوبر",
                2: "مشروب سوبر",
                description: "مشروب سوبر",
                3: "1",
                menus_price: "1",
                4: "7",
                category_id: "7",
                5: "تنزيل-(1).jpeg",
                image: "تنزيل-(1).jpeg",
            },
            {
                0: "35",
                media_id: "35",
                1: "سفن موهيتو",
                menus_name: "سفن موهيتو",
                2: "مشروب غازي سفن موهيتو",
                description: "مشروب غازي سفن موهيتو",
                3: "1",
                menus_price: "1",
                4: "7",
                category_id: "7",
                5: "images-(13).jpeg",
                image: "images-(13).jpeg",
            },
            {
                0: "36",
                media_id: "36",
                1: "ديو",
                menus_name: "ديو",
                2: "مشروب غازي ديو",
                description: "مشروب غازي ديو",
                3: "1",
                menus_price: "1",
                4: "7",
                category_id: "7",
                5: "81v+8GEzfWL.jpg",
                image: "81v+8GEzfWL.jpg",
            },
            {
                0: "37",
                media_id: "37",
                1: "ريتا أزرق",
                menus_name: "ريتا أزرق",
                2: "مشروب الطاقة ريتا أزرق",
                description: "مشروب الطاقة ريتا أزرق",
                3: "1.25",
                menus_price: "1.25",
                4: "7",
                category_id: "7",
                5: "images-(14).jpeg",
                image: "images-(14).jpeg",
            },
            {
                0: "38",
                media_id: "38",
                1: "ريتا أحمر",
                menus_name: "ريتا أحمر",
                2: "مشروب الطاقة ريتا أحمر",
                description: "مشروب الطاقة ريتا أحمر",
                3: "1.25",
                menus_price: "1.25",
                4: "7",
                category_id: "7",
                5: "images-(15).jpeg",
                image: "images-(15).jpeg",
            },
            {
                0: "41",
                media_id: "41",
                1: "بابكا",
                menus_name: "بابكا",
                2: "بابكا",
                description: "بابكا",
                3: "1.25",
                menus_price: "1.25",
                4: "8",
                category_id: "8",
                5: "images-(17).jpeg",
                image: "images-(17).jpeg",
            },
            {
                0: "42",
                media_id: "42",
                1: "كوكيز",
                menus_name: "كوكيز",
                2: "كوكيز",
                description: "كوكيز",
                3: "1.25",
                menus_price: "1.25",
                4: "8",
                category_id: "8",
                5: "1666869298_cookies.jpg",
                image: "1666869298_cookies.jpg",
            },
            {
                0: "43",
                media_id: "43",
                1: "كيك دمار",
                menus_name: "كيك دمار",
                2: "كيك دمار",
                description: "كيك دمار",
                3: "1.25",
                menus_price: "1.25",
                4: "8",
                category_id: "8",
                5: "images-(18).jpeg",
                image: "images-(18).jpeg",
            },
            {
                0: "44",
                media_id: "44",
                1: "بطاط خلطة",
                menus_name: "بطاط خلطة",
                2: "بطاط خلطة",
                description: "بطاط خلطة",
                3: "1.25",
                menus_price: "1.25",
                4: "8",
                category_id: "8",
                5: "201710040317481748.jpg",
                image: "201710040317481748.jpg",
            },
            {
                0: "54",
                media_id: "54",
                1: "سبايسي لحم",
                menus_name: "سبايسي لحم",
                2: "برجر سبايسي لحم",
                description: "برجر سبايسي لحم",
                3: "2.5",
                menus_price: "2.5",
                4: "6",
                category_id: "6",
                5: "1000157602.jpg",
                image: "1000157602.jpg",
            },
            {
                0: "55",
                media_id: "55",
                1: "سبايسي دجاج",
                menus_name: "سبايسي دجاج",
                2: "برجر سبايسي دجاج",
                description: "برجر سبايسي دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "6",
                category_id: "6",
                5: "1000157604.jpg",
                image: "1000157604.jpg",
            },
            {
                0: "60",
                media_id: "60",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "artcake-009.jpg",
                image: "artcake-009.jpg",
            },
            {
                0: "61",
                media_id: "61",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "artcake-002.jpg",
                image: "artcake-002.jpg",
            },
            {
                0: "62",
                media_id: "62",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "artcake-002.jpg",
                image: "artcake-002.jpg",
            },
            {
                0: "63",
                media_id: "63",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "artcake-002.jpg",
                image: "artcake-002.jpg",
            },
            {
                0: "64",
                media_id: "64",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "artcake-002.jpg",
                image: "artcake-002.jpg",
            },
            {
                0: "65",
                media_id: "65",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "artcake-002.jpg",
                image: "artcake-002.jpg",
            },
            {
                0: "66",
                media_id: "66",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "artcake-006.jpg",
                image: "artcake-006.jpg",
            },
            {
                0: "67",
                media_id: "67",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "artcake-029.jpg",
                image: "artcake-029.jpg",
            },
            {
                0: "68",
                media_id: "68",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "artcake-029.jpg",
                image: "artcake-029.jpg",
            },
            {
                0: "69",
                media_id: "69",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "artcake-029.jpg",
                image: "artcake-029.jpg",
            },
            {
                0: "70",
                media_id: "70",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "artcake-009.jpg",
                image: "artcake-009.jpg",
            },
            {
                0: "71",
                media_id: "71",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "artcake-029.jpg",
                image: "artcake-029.jpg",
            },
            {
                0: "72",
                media_id: "72",
                1: "كلاسيك دجاج",
                menus_name: "كلاسيك دجاج",
                2: "برجر كلاسيك دجاج",
                description: "برجر كلاسيك دجاج",
                3: "2.5",
                menus_price: "2.5",
                4: "7",
                category_id: "7",
                5: "artcake-009.jpg",
                image: "artcake-009.jpg",
            },
        ],
        4: [
            {
                0: "50",
                media_id: "50",
                1: "أقلام",
                menus_name: "أقلام",
                2: "أقلام",
                description: "أقلام",
                3: "50",
                menus_price: "50",
                4: "9",
                category_id: "9",
                5: "kFY7yiK77cZRrNL2vS9IJWw0nWJr15xP9T5Ryb8R.jpg",
                image: "kFY7yiK77cZRrNL2vS9IJWw0nWJr15xP9T5Ryb8R.jpg",
            },
            {
                0: "51",
                media_id: "51",
                1: "رول آب",
                menus_name: "رول آب",
                2: "رول اب",
                description: "رول اب",
                3: "40",
                menus_price: "40",
                4: "9",
                category_id: "9",
                5: "1000157520.jpg",
                image: "1000157520.jpg",
            },
            {
                0: "52",
                media_id: "52",
                1: "رأس شاحن سيارة",
                menus_name: "رأس شاحن سيارة",
                2: "رأس شاحن سيارة",
                description: "رأس شاحن سيارة",
                3: "7",
                menus_price: "7",
                4: "10",
                category_id: "10",
                5: "1000157525.jpg",
                image: "1000157525.jpg",
            },
            {
                0: "53",
                media_id: "53",
                1: "مروحة",
                menus_name: "مروحة",
                2: "مروحة",
                description: "مروحة",
                3: "17",
                menus_price: "17",
                4: "11",
                category_id: "11",
                5: "1000157537.jpg",
                image: "1000157537.jpg",
            },
        ],
    },
    categories: {
        1: [
            {
                0: "1",
                id: "1",
                1: "ارز",
                NAME: "ارز كبسة",
                2: "ارز كبسة",
                3: "1",
                restaurant_id: "1",
                4: "1",
                STATUS: "1",
                5: "1000140229.jpg",
                image: "1000140229.jpg",
                6: "1",
                media_id: "1",
                7: "2023-09-13 19:52:14",
                created_at: "2023-09-13 19:52:14",
                8: "2023-09-13 19:52:14",
                updated_at: "2023-09-13 19:52:14",
            },
            {
                0: "2",
                id: "2",
                1: "Test",
                NAME: "Rr",
                2: "Rr",
                3: "1",
                restaurant_id: "1",
                4: "1",
                STATUS: "1",
                5: "1000156205.jpg",
                image: "1000156205.jpg",
                6: "6",
                media_id: "6",
                7: "2023-09-15 13:58:48",
                created_at: "2023-09-15 13:58:48",
                8: "2023-09-15 13:58:48",
                updated_at: "2023-09-15 13:58:48",
            },
        ],
        2: [
            {
                0: "3",
                id: "3",
                1: "086",
                NAME: "اسود",
                2: "اسود",
                3: "2",
                restaurant_id: "2",
                4: "1",
                STATUS: "1",
                5: "1000157206.jpg",
                image: "1000157206.jpg",
                6: "8",
                media_id: "8",
                7: "2023-09-16 18:58:47",
                created_at: "2023-09-16 18:58:47",
                8: "2023-09-16 18:58:47",
                updated_at: "2023-09-16 18:58:47",
            },
            {
                0: "4",
                id: "4",
                1: "375",
                NAME: "375",
                2: "375",
                3: "2",
                restaurant_id: "2",
                4: "1",
                STATUS: "1",
                5: "1000157205.jpg",
                image: "1000157205.jpg",
                6: "9",
                media_id: "9",
                7: "2023-09-16 18:59:16",
                created_at: "2023-09-16 18:59:16",
                8: "2023-09-16 18:59:16",
                updated_at: "2023-09-16 18:59:16",
            },
            {
                0: "5",
                id: "5",
                1: "018",
                NAME: "018",
                2: "018",
                3: "2",
                restaurant_id: "2",
                4: "1",
                STATUS: "1",
                5: "1000157204.jpg",
                image: "1000157204.jpg",
                6: "10",
                media_id: "10",
                7: "2023-09-16 18:59:53",
                created_at: "2023-09-16 18:59:53",
                8: "2023-09-16 18:59:53",
                updated_at: "2023-09-16 18:59:53",
            },
        ],
        3: [
            {
                0: "7",
                id: "7",
                1: "مشروبات",
                NAME: "مشروبات منوعة",
                2: "مشروبات منوعة",
                3: "3",
                restaurant_id: "3",
                4: "1",
                STATUS: "1",
                5: "تنزيل.jpg",
                image: "تنزيل.jpg",
                6: "31",
                media_id: "31",
                7: "2023-09-17 07:24:22",
                created_at: "2023-09-17 07:24:22",
                8: "2023-09-17 07:24:22",
                updated_at: "2023-09-17 07:24:22",
            },
            {
                0: "6",
                id: "6",
                1: "فطاير تقديم",
                NAME: "فطاير",
                2: "فطاير",
                3: "3",
                restaurant_id: "3",
                4: "1",
                STATUS: "1",
                5: "تنزيل-(3).jpg",
                image: "تنزيل-(3).jpg",
                6: "39",
                media_id: "39",
                7: "2023-09-17 06:29:10",
                created_at: "2023-09-17 06:29:10",
                8: "2023-09-19 20:23:16",
                updated_at: "2023-09-19 20:23:16",
            },
            {
                0: "8",
                id: "8",
                1: "سويت",
                NAME: "سويت",
                2: "سويت",
                3: "3",
                restaurant_id: "3",
                4: "1",
                STATUS: "1",
                5: "images-(16).jpg",
                image: "images-(16).jpg",
                6: "40",
                media_id: "40",
                7: "2023-09-17 08:02:09",
                created_at: "2023-09-17 08:02:09",
                8: "2023-09-17 08:02:09",
                updated_at: "2023-09-17 08:02:09",
            },
            {
                0: "6",
                id: "6",
                1: "فطاير تقديم",
                NAME: "فطاير",
                2: "فطاير",
                3: "3",
                restaurant_id: "3",
                4: "1",
                STATUS: "1",
                5: "artcake-046.jpg",
                image: "artcake-046.jpg",
                6: "57",
                media_id: "57",
                7: "2023-09-17 06:29:10",
                created_at: "2023-09-17 06:29:10",
                8: "2023-09-19 20:23:16",
                updated_at: "2023-09-19 20:23:16",
            },
        ],
        4: [
            {
                0: "9",
                id: "9",
                1: "مطبوعات",
                NAME: "مطبوعات",
                2: "مطبوعات",
                3: "4",
                restaurant_id: "4",
                4: "1",
                STATUS: "1",
                5: "logo_1654265743.jpg",
                image: "logo_1654265743.jpg",
                6: "47",
                media_id: "47",
                7: "2023-09-17 09:09:19",
                created_at: "2023-09-17 09:09:19",
                8: "2023-09-17 09:09:19",
                updated_at: "2023-09-17 09:09:19",
            },
            {
                0: "10",
                id: "10",
                1: "الكترونيات",
                NAME: "الكترونيات",
                2: "الكترونيات",
                3: "4",
                restaurant_id: "4",
                4: "1",
                STATUS: "1",
                5: "images-(24).jpg",
                image: "images-(24).jpg",
                6: "48",
                media_id: "48",
                7: "2023-09-17 09:10:01",
                created_at: "2023-09-17 09:10:01",
                8: "2023-09-17 09:10:01",
                updated_at: "2023-09-17 09:10:01",
            },
            {
                0: "11",
                id: "11",
                1: "أدوات منزل",
                NAME: "أدوات منزل",
                2: "أدوات منزل",
                3: "4",
                restaurant_id: "4",
                4: "1",
                STATUS: "1",
                5: "images-(23).jpg",
                image: "images-(23).jpg",
                6: "49",
                media_id: "49",
                7: "2023-09-17 09:10:26",
                created_at: "2023-09-17 09:10:26",
                8: "2023-09-17 09:10:26",
                updated_at: "2023-09-17 09:10:26",
            },
        ],
    },
};
