export const menuItems = [
    {
        0: "26",
        media_id: "26",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "images.jpeg",
        image: "images.jpeg",
    },
    {
        0: "27",
        media_id: "27",
        1: "كلاسيك لحم",
        menus_name: "كلاسيك لحم",
        2: "برجر كلاسيك لحم",
        description: "برجر كلاسيك لحم",
        3: "2.5",
        menus_price: "2.5",
        4: "6",
        category_id: "6",
        5: "images-(3).jpeg",
        image: "images-(3).jpeg",
    },
    {
        0: "30",
        media_id: "30",
        1: "برجر مشروم",
        menus_name: "برجر مشروم",
        2: "برجر مشروم",
        description: "برجر مشروم",
        3: "2.5",
        menus_price: "2.5",
        4: "6",
        category_id: "6",
        5: "images-(7).jpeg",
        image: "images-(7).jpeg",
    },
    {
        0: "32",
        media_id: "32",
        1: "رد بول",
        menus_name: "رد بول",
        2: "مشروب الطاقة رد بول",
        description: "مشروب الطاقة رد بول",
        3: "1.25",
        menus_price: "1.25",
        4: "7",
        category_id: "7",
        5: "images-(11).jpeg",
        image: "images-(11).jpeg",
    },
    {
        0: "33",
        media_id: "33",
        1: "كود رِد",
        menus_name: "كود رِد",
        2: "مشروب الطاقة كود رِد",
        description: "مشروب الطاقة كود رِد",
        3: "1",
        menus_price: "1",
        4: "7",
        category_id: "7",
        5: "images-(12).jpeg",
        image: "images-(12).jpeg",
    },
    {
        0: "34",
        media_id: "34",
        1: "سوبر",
        menus_name: "سوبر",
        2: "مشروب سوبر",
        description: "مشروب سوبر",
        3: "1",
        menus_price: "1",
        4: "7",
        category_id: "7",
        5: "تنزيل-(1).jpeg",
        image: "تنزيل-(1).jpeg",
    },
    {
        0: "35",
        media_id: "35",
        1: "سفن موهيتو",
        menus_name: "سفن موهيتو",
        2: "مشروب غازي سفن موهيتو",
        description: "مشروب غازي سفن موهيتو",
        3: "1",
        menus_price: "1",
        4: "7",
        category_id: "7",
        5: "images-(13).jpeg",
        image: "images-(13).jpeg",
    },
    {
        0: "36",
        media_id: "36",
        1: "ديو",
        menus_name: "ديو",
        2: "مشروب غازي ديو",
        description: "مشروب غازي ديو",
        3: "1",
        menus_price: "1",
        4: "7",
        category_id: "7",
        5: "81v+8GEzfWL.jpg",
        image: "81v+8GEzfWL.jpg",
    },
    {
        0: "37",
        media_id: "37",
        1: "ريتا أزرق",
        menus_name: "ريتا أزرق",
        2: "مشروب الطاقة ريتا أزرق",
        description: "مشروب الطاقة ريتا أزرق",
        3: "1.25",
        menus_price: "1.25",
        4: "7",
        category_id: "7",
        5: "images-(14).jpeg",
        image: "images-(14).jpeg",
    },
    {
        0: "38",
        media_id: "38",
        1: "ريتا أحمر",
        menus_name: "ريتا أحمر",
        2: "مشروب الطاقة ريتا أحمر",
        description: "مشروب الطاقة ريتا أحمر",
        3: "1.25",
        menus_price: "1.25",
        4: "7",
        category_id: "7",
        5: "images-(15).jpeg",
        image: "images-(15).jpeg",
    },
    {
        0: "41",
        media_id: "41",
        1: "بابكا",
        menus_name: "بابكا",
        2: "بابكا",
        description: "بابكا",
        3: "1.25",
        menus_price: "1.25",
        4: "8",
        category_id: "8",
        5: "images-(17).jpeg",
        image: "images-(17).jpeg",
    },
    {
        0: "42",
        media_id: "42",
        1: "كوكيز",
        menus_name: "كوكيز",
        2: "كوكيز",
        description: "كوكيز",
        3: "1.25",
        menus_price: "1.25",
        4: "8",
        category_id: "8",
        5: "1666869298_cookies.jpg",
        image: "1666869298_cookies.jpg",
    },
    {
        0: "43",
        media_id: "43",
        1: "كيك دمار",
        menus_name: "كيك دمار",
        2: "كيك دمار",
        description: "كيك دمار",
        3: "1.25",
        menus_price: "1.25",
        4: "8",
        category_id: "8",
        5: "images-(18).jpeg",
        image: "images-(18).jpeg",
    },
    {
        0: "44",
        media_id: "44",
        1: "بطاط خلطة",
        menus_name: "بطاط خلطة",
        2: "بطاط خلطة",
        description: "بطاط خلطة",
        3: "1.25",
        menus_price: "1.25",
        4: "8",
        category_id: "8",
        5: "201710040317481748.jpg",
        image: "201710040317481748.jpg",
    },
    {
        0: "54",
        media_id: "54",
        1: "سبايسي لحم",
        menus_name: "سبايسي لحم",
        2: "برجر سبايسي لحم",
        description: "برجر سبايسي لحم",
        3: "2.5",
        menus_price: "2.5",
        4: "6",
        category_id: "6",
        5: "1000157602.jpg",
        image: "1000157602.jpg",
    },
    {
        0: "55",
        media_id: "55",
        1: "سبايسي دجاج",
        menus_name: "سبايسي دجاج",
        2: "برجر سبايسي دجاج",
        description: "برجر سبايسي دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "6",
        category_id: "6",
        5: "1000157604.jpg",
        image: "1000157604.jpg",
    },
    {
        0: "60",
        media_id: "60",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "artcake-009.jpg",
        image: "artcake-009.jpg",
    },
    {
        0: "61",
        media_id: "61",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "artcake-002.jpg",
        image: "artcake-002.jpg",
    },
    {
        0: "62",
        media_id: "62",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "artcake-002.jpg",
        image: "artcake-002.jpg",
    },
    {
        0: "63",
        media_id: "63",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "artcake-002.jpg",
        image: "artcake-002.jpg",
    },
    {
        0: "64",
        media_id: "64",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "artcake-002.jpg",
        image: "artcake-002.jpg",
    },
    {
        0: "65",
        media_id: "65",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "artcake-002.jpg",
        image: "artcake-002.jpg",
    },
    {
        0: "66",
        media_id: "66",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "artcake-006.jpg",
        image: "artcake-006.jpg",
    },
    {
        0: "67",
        media_id: "67",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "artcake-029.jpg",
        image: "artcake-029.jpg",
    },
    {
        0: "68",
        media_id: "68",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "artcake-029.jpg",
        image: "artcake-029.jpg",
    },
    {
        0: "69",
        media_id: "69",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "artcake-029.jpg",
        image: "artcake-029.jpg",
    },
    {
        0: "70",
        media_id: "70",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "artcake-009.jpg",
        image: "artcake-009.jpg",
    },
    {
        0: "71",
        media_id: "71",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "artcake-029.jpg",
        image: "artcake-029.jpg",
    },
    {
        0: "72",
        media_id: "72",
        1: "كلاسيك دجاج",
        menus_name: "كلاسيك دجاج",
        2: "برجر كلاسيك دجاج",
        description: "برجر كلاسيك دجاج",
        3: "2.5",
        menus_price: "2.5",
        4: "7",
        category_id: "7",
        5: "artcake-009.jpg",
        image: "artcake-009.jpg",
    },
];

export const categories = [
    {
        0: "7",
        id: "7",
        1: "مشروبات",
        NAME: "مشروبات منوعة",
        2: "مشروبات منوعة",
        3: "3",
        restaurant_id: "3",
        4: "1",
        STATUS: "1",
        5: "تنزيل.jpg",
        image: "تنزيل.jpg",
        6: "31",
        media_id: "31",
        7: "2023-09-17 07:24:22",
        created_at: "2023-09-17 07:24:22",
        8: "2023-09-17 07:24:22",
        updated_at: "2023-09-17 07:24:22",
    },
    {
        0: "6",
        id: "6",
        1: "فطاير تقديم",
        NAME: "فطاير",
        2: "فطاير",
        3: "3",
        restaurant_id: "3",
        4: "1",
        STATUS: "1",
        5: "تنزيل-(3).jpg",
        image: "تنزيل-(3).jpg",
        6: "39",
        media_id: "39",
        7: "2023-09-17 06:29:10",
        created_at: "2023-09-17 06:29:10",
        8: "2023-09-19 20:23:16",
        updated_at: "2023-09-19 20:23:16",
    },
    {
        0: "8",
        id: "8",
        1: "سويت",
        NAME: "سويت",
        2: "سويت",
        3: "3",
        restaurant_id: "3",
        4: "1",
        STATUS: "1",
        5: "images-(16).jpg",
        image: "images-(16).jpg",
        6: "40",
        media_id: "40",
        7: "2023-09-17 08:02:09",
        created_at: "2023-09-17 08:02:09",
        8: "2023-09-17 08:02:09",
        updated_at: "2023-09-17 08:02:09",
    },
    {
        0: "6",
        id: "6",
        1: "فطاير تقديم",
        NAME: "فطاير",
        2: "فطاير",
        3: "3",
        restaurant_id: "3",
        4: "1",
        STATUS: "1",
        5: "artcake-046.jpg",
        image: "artcake-046.jpg",
        6: "57",
        media_id: "57",
        7: "2023-09-17 06:29:10",
        created_at: "2023-09-17 06:29:10",
        8: "2023-09-19 20:23:16",
        updated_at: "2023-09-19 20:23:16",
    },
];
